### ISSUE TITLE
Unique Objects based on Key

### ISSUE THREAD

**Issue by LaughDonor** [MansurAliKoroglu/enforce-unique#3]
I would like to offer an idea for extending the functionality of `.enforce`. Could we add a `key` parameter to the constructor which is a string key of the `UniqueComparable` object that gets returned by `.enforce`? The `store` could save that keyed value and return the full object if it passes.

Example if we wanted an object's `code` key to be unique:

```javascript
const myUniqueEnforcer = new UniqueEnforcer("code");  // Understands that it'll be working with objects and "code" is a key of enforcable objects.

let value = myUniqueEnforcer({name: "Bobby Brown", code: "BB"}) // Works, saves "BB" in store
// value === {name: "Bobby Brown", code: "BB"}
 
value = myUniqueEnforcer({name: "Billy Bob", code: "BB"}) // Fails, since "BB" is already in store
// EnforceLimitError is raised

value = myUniqueEnforcer({name: "Bobby Brown", code: "BB2"}) // Works, saves "BB2" in store
// value === {name: "Bobby Brown", code: "BB2"}
```

**Comment by Shinigami92** [comment]
This sounds like an interesting feature to me

I would encourage to use an options object for the constructor, so it is more future proof and can enhance without introducing breaking changes.

something like: `new UniqueEnforcer({ key: 'code' })`

**Comment by MansurAliKoroglu** [comment]
Hi, thanks a lot for the idea!

Before we dive deeper, I wanted to point out that it’s currently possible to generate a whole database model or JavaScript Object with some unique fields without needing this suggested feature. Here’s an example:

```js
import { UniqueEnforcer } from 'enforce-unique';

const uniqueEnforcerCode = new UniqueEnforcer();

function createRandomUser() {
  const name = faker.person.fullName();
  const code = uniqueEnforcerCode.enforce(() =>
    faker.datatype.uuid(),
    {
      maxTime: 50,
      maxRetries: 50,
    }
  );

  return {
    name,
    code,
  };
}
```

Does this approach feel cumbersome or inconvenient for your needs? Or is there something specific that this method doesn’t cover for you?

I’m asking because I want to keep the package as simple as possible and avoid adding complexity unless it’s really necessary. However, if you feel that the new feature would provide significant value, I’m open to considering it. Let’s discuss further!
